"""Make initial table

Revision ID: b8e780de54cc
Revises: 
Create Date: 2022-02-14 14:54:06.646424

"""
from alembic import op
import sqlalchemy as sa
import src
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8e780de54cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_files',
    sa.Column('id', src.models.UUID(as_uuid=True), nullable=False),
    sa.Column('json_body', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_files')
    # ### end Alembic commands ###